openapi: 3.0.1
info:
  title: Price Comparator
  description: Food market price data
  version: 1.0.0
servers:
- url: localhost:3000/api/v1
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples:
    get:
      tags:
      - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
      - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /examples/{id}:
    get:
      tags:
      - Examples
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /products:
    get:
      tags:
      - Products
      description: Fetch all products
      responses:
        200:
          description: Returns all products
          content: {}
    post:
      tags:
      - Products
      description: Create a new products
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductBody'
        required: true
      responses:
        200:
          description: Returns all products
          content: {}
  /products/{id}:
    get:
      tags:
      - Products
      parameters:
      - name: id
        in: path
        description: The id of the products to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the products with the specified id
          content: {}
        404:
          description: products not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    ProductBody:
      title: product
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: Agua sin gas
        price:
          type: number
          example: 19
    ExampleBody:
      title: product
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
